import * as assert from "assert";
import * as path from "path";
import { rollup } from "rollup";
import { decode } from "@jridgewell/sourcemap-codec";
import dts from "../src/index.js";
import { Harness } from "./utils.js";

export default (t: Harness) => {
  t.test("sourcemap/line-mappings-preserved", async () => {
    /**
     * This test verifies that sourcemaps generated by rollup-plugin-dts
     * preserve proper line-by-line mappings for each identifier.
     *
     * The issue: When bundling .d.ts files, the output sourcemap loses
     * detailed mappings. Instead of mapping each identifier to its correct
     * source position, multiple identifiers on the same output line
     * all map to the same position.
     *
     * Input (from tsc):
     *   export type User = { id: string; name: string; };
     *
     * Expected output mappings:
     *   - 'type' maps to 'export' or 'type' in source
     *   - 'User' maps to 'User' in source
     *   - 'id' maps to 'id' in source
     *   - 'name' maps to 'name' in source
     *
     * Actual (broken) output mappings:
     *   - All identifiers on line 1 map to same position (col 7)
     *   - Lines 2+ have minimal or no mappings
     */

    const dir = path.resolve(process.cwd(), "tests/sourcemap-fixtures");

    const bundle = await rollup({
      input: path.join(dir, "index.d.ts"),
      plugins: [dts()],
      onwarn() {},
    });

    const result = await bundle.generate({
      format: "es",
      sourcemap: true,
    });

    const map = result.output[0].map!;

    // Parse the mappings to check individual segment positions
    // decode returns: [generatedCol, sourceIndex, sourceLine, sourceCol, nameIndex?][][]
    const decoded = decode(map.mappings);

    // The output code should be:
    // Line 1: type User = {
    // Line 2:     id: string;
    // Line 3:     name: string;
    // Line 4: };
    // Line 5: (empty)
    // Line 6: export type { User };

    // Check that line 1 has multiple distinct column mappings
    // (not all pointing to the same source position)
    const line1 = decoded[0] || [];
    assert.ok(
      line1.length >= 2,
      `Line 1 should have at least 2 mapping segments, got ${line1.length}. ` +
        `Mappings: ${map.mappings}`,
    );

    // The segments on line 1 should map to different source columns
    // If they all map to the same column, the sourcemap is broken
    const line1SourceCols = line1.map((seg) => seg[3]); // sourceColumn is index 3
    const uniqueSourceCols = new Set(line1SourceCols);
    assert.ok(
      uniqueSourceCols.size > 1,
      `Line 1 segments should map to different source columns, but all map to: ${[...uniqueSourceCols].join(", ")}. ` +
        `This breaks Go-to-Definition in VSCode.`,
    );

    // Check that line 2 (id: string;) has mapping segments
    const line2 = decoded[1] || [];
    assert.ok(
      line2.length >= 1,
      `Line 2 should have mapping segments for 'id: string;', got ${line2.length}`,
    );

    // Check that line 3 (name: string;) has mapping segments
    const line3 = decoded[2] || [];
    assert.ok(
      line3.length >= 1,
      `Line 3 should have mapping segments for 'name: string;', got ${line3.length}`,
    );

    // Most importantly: verify the mappings point to correct source lines
    // Line 2 in output (id: string;) should map to line 2 in source
    if (line2.length > 0 && line2[0]!.length >= 4) {
      const sourceLine = line2[0]![2]!; // sourceLine is index 2
      assert.strictEqual(
        sourceLine,
        1, // 0-indexed, so line 2 is index 1
        `Line 2 'id: string;' should map to source line 2, got ${sourceLine + 1}`,
      );
    }

    // Line 3 in output (name: string;) should map to line 3 in source
    if (line3.length > 0 && line3[0]!.length >= 4) {
      const sourceLine = line3[0]![2]!; // sourceLine is index 2
      assert.strictEqual(
        sourceLine,
        2, // 0-indexed, so line 3 is index 2
        `Line 3 'name: string;' should map to source line 3, got ${sourceLine + 1}`,
      );
    }
  });

  t.test("sourcemap/input-map-chained", async () => {
    /**
     * This test verifies that when input .d.ts files have associated
     * .d.ts.map files, the output sourcemap chains through to the
     * original source file.
     *
     * The input .d.ts.map file maps:
     *   index.d.ts -> ../src/index.ts
     *
     * The output sourcemap should ultimately map:
     *   output.d.ts -> ../src/index.ts (the original source)
     *
     * NOT:
     *   output.d.ts -> index.d.ts (the intermediate file)
     */

    const dir = path.resolve(process.cwd(), "tests/sourcemap-fixtures");

    const bundle = await rollup({
      input: path.join(dir, "index.d.ts"),
      plugins: [dts()],
      onwarn() {},
    });

    const result = await bundle.generate({
      format: "es",
      sourcemap: true,
    });

    const map = result.output[0].map!;

    // The sources should include the original .ts file, not just the .d.ts file
    // Currently this fails because the input sourcemap is not being read
    const hasOriginalSource = map.sources.some(
      (source) => source.endsWith("index.ts") && !source.endsWith(".d.ts"),
    );

    assert.ok(
      hasOriginalSource,
      `Sourcemap should chain through to original source file (*.ts), ` +
        `but only has: ${map.sources.join(", ")}. ` +
        `The input .d.ts.map file is not being read/chained.`,
    );
  });

  t.test("sourcemap/inline-base64", async () => {
    /**
     * This test verifies that inline base64-encoded sourcemaps are correctly
     * parsed and chained to the original source file.
     *
     * The input file has a sourceMappingURL comment with a data URL:
     *   //# sourceMappingURL=data:application/json;base64,...
     */

    const dir = path.resolve(process.cwd(), "tests/sourcemap-fixtures");

    const bundle = await rollup({
      input: path.join(dir, "inline-base64.d.ts"),
      plugins: [dts()],
      onwarn() {},
    });

    const result = await bundle.generate({
      format: "es",
      sourcemap: true,
    });

    const map = result.output[0].map!;

    // The sources should chain through to the original .ts file
    const hasOriginalSource = map.sources.some(
      (source) => source.endsWith("index.ts") && !source.endsWith(".d.ts"),
    );

    assert.ok(
      hasOriginalSource,
      `Inline base64 sourcemap should chain to original source (*.ts), ` +
        `but only has: ${map.sources.join(", ")}`,
    );

    // Verify line mappings are preserved
    const decoded = decode(map.mappings);
    const linesWithMappings = decoded.filter((line) => line.length > 0).length;
    assert.ok(
      linesWithMappings >= 4,
      `Should have at least 4 lines with mappings, got ${linesWithMappings}`,
    );
  });

  t.test("sourcemap/inline-urlencoded", async () => {
    /**
     * This test verifies that inline URL-encoded sourcemaps are correctly
     * parsed and chained to the original source file.
     *
     * The input file has a sourceMappingURL comment with a data URL:
     *   //# sourceMappingURL=data:application/json,%7B%22version%22...
     */

    const dir = path.resolve(process.cwd(), "tests/sourcemap-fixtures");

    const bundle = await rollup({
      input: path.join(dir, "inline-urlencoded.d.ts"),
      plugins: [dts()],
      onwarn() {},
    });

    const result = await bundle.generate({
      format: "es",
      sourcemap: true,
    });

    const map = result.output[0].map!;

    // The sources should chain through to the original .ts file
    const hasOriginalSource = map.sources.some(
      (source) => source.endsWith("index.ts") && !source.endsWith(".d.ts"),
    );

    assert.ok(
      hasOriginalSource,
      `Inline URL-encoded sourcemap should chain to original source (*.ts), ` +
        `but only has: ${map.sources.join(", ")}`,
    );

    // Verify line mappings are preserved
    const decoded = decode(map.mappings);
    const linesWithMappings = decoded.filter((line) => line.length > 0).length;
    assert.ok(
      linesWithMappings >= 4,
      `Should have at least 4 lines with mappings, got ${linesWithMappings}`,
    );
  });

  t.test("sourcemap/file-reference", async () => {
    /**
     * This test verifies that sourceMappingURL file references (not adjacent
     * .d.ts.map files) are correctly resolved and chained.
     *
     * The input file has:
     *   //# sourceMappingURL=maps/types.d.ts.map
     *
     * The map file is in a subdirectory, not adjacent to the .d.ts file.
     */

    const dir = path.resolve(process.cwd(), "tests/sourcemap-fixtures/file-ref");

    const bundle = await rollup({
      input: path.join(dir, "types.d.ts"),
      plugins: [dts()],
      onwarn() {},
    });

    const result = await bundle.generate({
      format: "es",
      sourcemap: true,
    });

    const map = result.output[0].map!;

    // The sources should chain through to the original .ts file
    const hasOriginalSource = map.sources.some(
      (source) => source.endsWith("index.ts") && !source.endsWith(".d.ts"),
    );

    assert.ok(
      hasOriginalSource,
      `File reference sourcemap should chain to original source (*.ts), ` +
        `but only has: ${map.sources.join(", ")}`,
    );

    // Verify line mappings are preserved
    const decoded = decode(map.mappings);
    const linesWithMappings = decoded.filter((line) => line.length > 0).length;
    assert.ok(
      linesWithMappings >= 4,
      `Should have at least 4 lines with mappings, got ${linesWithMappings}`,
    );
  });

  t.test("sourcemap/query-string-stripped", async () => {
    /**
     * This test verifies that query strings in sourceMappingURL comments
     * are stripped when resolving the map file path.
     *
     * The input file has:
     *   //# sourceMappingURL=query-string.d.ts.map?v=12345
     *
     * The actual file is query-string.d.ts.map (without query string).
     */

    const dir = path.resolve(process.cwd(), "tests/sourcemap-fixtures");

    const bundle = await rollup({
      input: path.join(dir, "query-string.d.ts"),
      plugins: [dts()],
      onwarn() {},
    });

    const result = await bundle.generate({
      format: "es",
      sourcemap: true,
    });

    const map = result.output[0].map!;

    // The sources should chain through to the original .ts file
    const hasOriginalSource = map.sources.some(
      (source) => source.endsWith("index.ts") && !source.endsWith(".d.ts"),
    );

    assert.ok(
      hasOriginalSource,
      `Query string should be stripped from sourceMappingURL, ` +
        `but sources only has: ${map.sources.join(", ")}`,
    );
  });
};
